language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
install:
  - yarn install
script:
  - yarn build
script:
  - if [ $TRAVIS_BRANCH = 'master' ]; then node ./deploy.js; fi

