language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
install:
  - yarn install
script:
  - yarn build
script:
  if: branch = master
  - CLIENT_ID=${CLIENT_ID} CLIENT_SECRET=${CLIENT_SECRET} EXTENSION_ID=${EXTENSION_ID} REFRESH_TOKEN=${REFRESH_TOKEN} node ./deploy.js

